// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import "controllers"
import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import { Application } from '@hotwired/stimulus'
import ScrollProgress from 'stimulus-scroll-progress'

const application = Application.start()
application.register('scroll-progress', ScrollProgress)

import { Application } from '@hotwired/stimulus'
import Sortable from 'stimulus-sortable'

const application = Application.start()
application.register('sortable', Sortable)
